// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (f71abc090ff6016f71d2bd9a38fe6123)",
    jsVersion: "33850bbf1605a31a47132fd53b8f20acd85d3a39",
    wasmJsSize:  432469,
    wasmVersion: "48a2c419ca2aed742f3a3dacd3650572",
    wasmSize: 2919478,
    jsSize:  0,
    buildSeed:  1586217460591,
};
