// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (28b7876d7049716694f6bf1212eec512)",
    jsVersion: "8cdb72e02e33c7b21628229a6973a872ca8c274a",
    wasmJsSize:  185683,
    wasmVersion: "0cb454fe2294e2ceea087976182362ce",
    wasmSize: 1820697,
    jsSize:  6670000,
    buildSeed:  1586041013785,
};
